routes/login_google.py
import os
import pathlib

import requests
from flask import Blueprint, session, abort, redirect, request,url_for,jsonify,render_template
from flask_login import (UserMixin, login_required, login_user, logout_user, current_user)
from google.oauth2 import id_token
from google_auth_oauthlib.flow import Flow
from pip._vendor import cachecontrol
import google.auth.transport.requests

from models.models import User,Address,Credencial
from utils.db import db
from methods.requests import Request
from decorators.flask_decorators import login_is_required

GOOGLE_CLIENT_ID = "191643232132-e96g0rrr3soareb2fda05hep1db4ru6p.apps.googleusercontent.com"
client_secrets_file = os.path.join(pathlib.Path(__file__).parent, "../client_secret.json")

os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "1"

flow = Flow.from_client_secrets_file(
    client_secrets_file=client_secrets_file,
    scopes = ["https://www.googleapis.com/auth/userinfo.profile","https://www.googleapis.com/auth/userinfo.email","openid"],
    redirect_uri = 'http://127.0.0.1:5000/callback',
)


Login_Google = Blueprint("Login_Google",__name__)







@Login_Google.route("/protected_area",endpoint = 'ProtectedArea')
@login_is_required(session)
def ProtectedArea():
    return f"Hello {session['name']}! <br/> <a href='/logout'><button>Logout</button></a>"


@Login_Google.route("/google_login")
def Login():
    autorization_url,state = flow.authorization_url()
    session['state'] = state
    return redirect(autorization_url)




@Login_Google.route("/callback")
def callback():
    flow.fetch_token(authorization_response=request.url)

    try:
        if not session["state"] == request.args["state"]:
            abort(500)  # State does not match!
    except:
        pass

    credentials = flow.credentials
    request_session = requests.session()
    cached_session = cachecontrol.CacheControl(request_session)
    token_request = google.auth.transport.requests.Request(session=cached_session)

    id_info = id_token.verify_oauth2_token(
        id_token=credentials._id_token,
        request=token_request,
        audience=GOOGLE_CLIENT_ID
    )

    user_google_id = Credencial.query.filter_by(campo = id_info.get("sub")).first()

    print(user_google_id)
    if user_google_id:
        user = User.query.filter_by(id_user = user_google_id.id_user).first()
        session['user_id'] = user.getId()
        return redirect(url_for('Login.profile'))
    else: 
        

        user = User(id_info.get("name"),id_info.get("email"),None)
            
        db.session.add(user)
        db.session.commit()
            
        google_id = Credencial('google_id',id_info.get("sub"),'google',user.getId())
        db.session.add(google_id)

        db.session.commit()

        session['user_id'] = user.getId()
    
        return redirect(url_for('Login_Google.googleAddress'))


@Login_Google.route("/google_login/register-address",methods=['GET','POST'])
def googleAddress():
    if request.method == 'POST':
        form = Request('province','city','district')

        address = Address(form['province'],form['city'],form['district'],'1','1')
        db.session.add(address)
        db.session.commit()

        user = User.query.filter_by(id_user = session['user_id']).first()
        user.id_address = address.id_address
        db.session.commit()
        return redirect(url_for('Login.profile'))
        
    return render_template('login/address.html')

templates/login/address.html
{% extends "base.html" %}
{% block title %}
    Si
{% endblock %}

{% block head %}
    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base_css.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login/login_css.css') }}">
    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- SCROOL REVEAL -->
    <script src="https://unpkg.com/scrollreveal"></script>

{% endblock %}


{% block content %}
    <h1>Completa estos pasos para terminar tu cuenta!!!</h1>
    <form method="post">
        <div class="imgcontainer">
          <img src="img_avatar2.png" alt="" class="avatar">
        </div>
      
        <div class="container">
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for msg in messages %}
                <p>{{msg}}</p>
              {% endfor %}
            {% endif %}
          {% endwith %}

          
          
          <input type="province" placeholder="Enter Province" name="province" required>
          
          <input type="city" placeholder="Enter city" name="city" required>
          
          <input type="district" placeholder="Enter district" name="district" required>
          
          <button type="submit">Sing In</button>
          
        </div>
      
        
    </form>
{% endblock %}

templates/login/login.html
{% extends "base.html" %}
{% block title %}
    Login
{% endblock %}

{% block head %}
    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base_css.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login/login_css.css') }}">
    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- SCROOL REVEAL -->
    <script src="https://unpkg.com/scrollreveal"></script>

{% endblock %}


{% block content %}
    <h1>Estas en Login!!!</h1>
    <form method="post">
        <div class="imgcontainer">
          <img src="img_avatar2.png" alt="" class="avatar">
        </div>
      
        <div class="container">
          <label for="uname"><b>Username</b></label>
          <input type="text" placeholder="Enter Username" name="username" required>
      
          <label for="psw"><b>Password</b></label>
          <input type="password" placeholder="Enter Password" name="password" required>
      
          <button type="submit">Login</button>
          <label>
            <input type="checkbox" checked="checked" name="remember"> Remember me
          </label>
        </div>
    </form>
    <a href="{{ url_for('Login.singin') }}"> Sing In</a>
{% endblock %}

templates/login/profile.html
{% extends "base.html" %}
{% block title %}
    Profile
{% endblock %}



{% block content %}
    <h1>Estas en Profile!!!</h1>
    <h2>{{g.user.username}}</h2>
    <h2>{{g.user.id}}</h2>
{% endblock %}

templates/login/singin.html
{% extends "base.html" %}
{% block title %}
    Sing In
{% endblock %}

{% block head %}
    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base_css.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/login/login_css.css') }}">
    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <!-- SCROOL REVEAL -->
    <script src="https://unpkg.com/scrollreveal"></script>

{% endblock %}


{% block content %}
    <h1>Estas en Sing In!!!</h1>
    <form method="post">
        <div class="imgcontainer">
          <img src="img_avatar2.png" alt="" class="avatar">
        </div>
      
        <div class="container">
          <label for="uname"><b>Username</b></label>
          <input type="text" placeholder="Enter Username" name="username" required>
          
          {% with messages = get_flashed_messages() %}
            {% if messages %}
              {% for msg in messages %}
                <p>{{msg}}</p>
              {% endfor %}
            {% endif %}
          {% endwith %}

          <label for="psw"><b>Password</b></label>
          
          <input type="password" placeholder="Enter Password" name="password" required>
          
          <input type="province" placeholder="Enter Province" name="province" required>
          
          <input type="city" placeholder="Enter city" name="city" required>
          
          <input type="district" placeholder="Enter district" name="district" required>
          
          <button type="submit">Sing In</button>
          
        </div>
      
        
    </form>
    <a href="{{ url_for('Login_Google.Login') }}"> Google</a>
    <a href="{{ url_for('Login.login') }}"> Login</a>
{% endblock %}